/* tslint:disable */
/* eslint-disable */
/**
 * Car Rental API
 * Backend API for Car Rental Application
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookingStatus } from './BookingStatus';
import {
    BookingStatusFromJSON,
    BookingStatusFromJSONTyped,
    BookingStatusToJSON,
    BookingStatusToJSONTyped,
} from './BookingStatus';

/**
 * 
 * @export
 * @interface BookingUpdate
 */
export interface BookingUpdate {
    /**
     * 
     * @type {Date}
     * @memberof BookingUpdate
     */
    startDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof BookingUpdate
     */
    endDate?: Date | null;
    /**
     * 
     * @type {BookingStatus}
     * @memberof BookingUpdate
     */
    status?: BookingStatus | null;
    /**
     * 
     * @type {Date}
     * @memberof BookingUpdate
     */
    pickupDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof BookingUpdate
     */
    returnDate?: Date | null;
}



/**
 * Check if a given object implements the BookingUpdate interface.
 */
export function instanceOfBookingUpdate(value: object): value is BookingUpdate {
    return true;
}

export function BookingUpdateFromJSON(json: any): BookingUpdate {
    return BookingUpdateFromJSONTyped(json, false);
}

export function BookingUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'startDate': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'endDate': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
        'status': json['status'] == null ? undefined : BookingStatusFromJSON(json['status']),
        'pickupDate': json['pickup_date'] == null ? undefined : (new Date(json['pickup_date'])),
        'returnDate': json['return_date'] == null ? undefined : (new Date(json['return_date'])),
    };
}

export function BookingUpdateToJSON(json: any): BookingUpdate {
    return BookingUpdateToJSONTyped(json, false);
}

export function BookingUpdateToJSONTyped(value?: BookingUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start_date': value['startDate'] == null ? undefined : ((value['startDate'] as any).toISOString().substring(0,10)),
        'end_date': value['endDate'] == null ? undefined : ((value['endDate'] as any).toISOString().substring(0,10)),
        'status': BookingStatusToJSON(value['status']),
        'pickup_date': value['pickupDate'] == null ? undefined : ((value['pickupDate'] as any).toISOString().substring(0,10)),
        'return_date': value['returnDate'] == null ? undefined : ((value['returnDate'] as any).toISOString().substring(0,10)),
    };
}

