/* tslint:disable */
/* eslint-disable */
/**
 * Car Rental API
 * Backend API for Car Rental Application
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Currency } from './Currency';
import {
    CurrencyFromJSON,
    CurrencyFromJSONTyped,
    CurrencyToJSON,
    CurrencyToJSONTyped,
} from './Currency';

/**
 * 
 * @export
 * @interface BookingCreate
 */
export interface BookingCreate {
    /**
     * ID of the car being booked
     * @type {number}
     * @memberof BookingCreate
     */
    carId: number;
    /**
     * Start date of the booking period
     * @type {Date}
     * @memberof BookingCreate
     */
    startDate: Date;
    /**
     * End date of the booking period
     * @type {Date}
     * @memberof BookingCreate
     */
    endDate: Date;
    /**
     * Time when the car will be picked up on start_date (UTC time)
     * @type {string}
     * @memberof BookingCreate
     */
    plannedPickupTime: string;
    /**
     * Currency code of the booking
     * @type {Currency}
     * @memberof BookingCreate
     */
    currencyCode: Currency;
}



/**
 * Check if a given object implements the BookingCreate interface.
 */
export function instanceOfBookingCreate(value: object): value is BookingCreate {
    if (!('carId' in value) || value['carId'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    if (!('plannedPickupTime' in value) || value['plannedPickupTime'] === undefined) return false;
    if (!('currencyCode' in value) || value['currencyCode'] === undefined) return false;
    return true;
}

export function BookingCreateFromJSON(json: any): BookingCreate {
    return BookingCreateFromJSONTyped(json, false);
}

export function BookingCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'carId': json['car_id'],
        'startDate': (new Date(json['start_date'])),
        'endDate': (new Date(json['end_date'])),
        'plannedPickupTime': json['planned_pickup_time'],
        'currencyCode': CurrencyFromJSON(json['currency_code']),
    };
}

export function BookingCreateToJSON(json: any): BookingCreate {
    return BookingCreateToJSONTyped(json, false);
}

export function BookingCreateToJSONTyped(value?: BookingCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'car_id': value['carId'],
        'start_date': ((value['startDate']).toISOString().substring(0,10)),
        'end_date': ((value['endDate']).toISOString().substring(0,10)),
        'planned_pickup_time': value['plannedPickupTime'],
        'currency_code': CurrencyToJSON(value['currencyCode']),
    };
}

