/* tslint:disable */
/* eslint-disable */
/**
 * Car Rental API
 * Backend API for Car Rental Application
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookingCreate
 */
export interface BookingCreate {
    /**
     * ID of the user making the booking
     * @type {number}
     * @memberof BookingCreate
     */
    userId: number;
    /**
     * ID of the car being booked
     * @type {number}
     * @memberof BookingCreate
     */
    carId: number;
    /**
     * Start date of the booking period
     * @type {Date}
     * @memberof BookingCreate
     */
    startDate: Date;
    /**
     * End date of the booking period
     * @type {Date}
     * @memberof BookingCreate
     */
    endDate: Date;
}

/**
 * Check if a given object implements the BookingCreate interface.
 */
export function instanceOfBookingCreate(value: object): value is BookingCreate {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('carId' in value) || value['carId'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    return true;
}

export function BookingCreateFromJSON(json: any): BookingCreate {
    return BookingCreateFromJSONTyped(json, false);
}

export function BookingCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'carId': json['car_id'],
        'startDate': (new Date(json['start_date'])),
        'endDate': (new Date(json['end_date'])),
    };
}

export function BookingCreateToJSON(json: any): BookingCreate {
    return BookingCreateToJSONTyped(json, false);
}

export function BookingCreateToJSONTyped(value?: BookingCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
        'car_id': value['carId'],
        'start_date': ((value['startDate']).toISOString().substring(0,10)),
        'end_date': ((value['endDate']).toISOString().substring(0,10)),
    };
}

