/* tslint:disable */
/* eslint-disable */
/**
 * Car Rental API
 * Backend API for Car Rental Application
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const BookingStatus = {
    Planned: 'PLANNED',
    Active: 'ACTIVE',
    Completed: 'COMPLETED',
    Canceled: 'CANCELED',
    Overdue: 'OVERDUE'
} as const;
export type BookingStatus = typeof BookingStatus[keyof typeof BookingStatus];


export function instanceOfBookingStatus(value: any): boolean {
    for (const key in BookingStatus) {
        if (Object.prototype.hasOwnProperty.call(BookingStatus, key)) {
            if (BookingStatus[key as keyof typeof BookingStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BookingStatusFromJSON(json: any): BookingStatus {
    return BookingStatusFromJSONTyped(json, false);
}

export function BookingStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingStatus {
    return json as BookingStatus;
}

export function BookingStatusToJSON(value?: BookingStatus | null): any {
    return value as any;
}

export function BookingStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): BookingStatus {
    return value as BookingStatus;
}

