/* tslint:disable */
/* eslint-disable */
/**
 * Car Rental API
 * Backend API for Car Rental Application
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Booking } from './Booking';
import {
    BookingFromJSON,
    BookingFromJSONTyped,
    BookingToJSON,
    BookingToJSONTyped,
} from './Booking';

/**
 * 
 * @export
 * @interface PaginatedResponseBooking
 */
export interface PaginatedResponseBooking {
    /**
     * 
     * @type {Array<Booking>}
     * @memberof PaginatedResponseBooking
     */
    items: Array<Booking>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedResponseBooking
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedResponseBooking
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedResponseBooking
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedResponseBooking
     */
    pages: number;
}

/**
 * Check if a given object implements the PaginatedResponseBooking interface.
 */
export function instanceOfPaginatedResponseBooking(value: object): value is PaginatedResponseBooking {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('pages' in value) || value['pages'] === undefined) return false;
    return true;
}

export function PaginatedResponseBookingFromJSON(json: any): PaginatedResponseBooking {
    return PaginatedResponseBookingFromJSONTyped(json, false);
}

export function PaginatedResponseBookingFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponseBooking {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(BookingFromJSON)),
        'total': json['total'],
        'page': json['page'],
        'pageSize': json['page_size'],
        'pages': json['pages'],
    };
}

export function PaginatedResponseBookingToJSON(json: any): PaginatedResponseBooking {
    return PaginatedResponseBookingToJSONTyped(json, false);
}

export function PaginatedResponseBookingToJSONTyped(value?: PaginatedResponseBooking | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(BookingToJSON)),
        'total': value['total'],
        'page': value['page'],
        'page_size': value['pageSize'],
        'pages': value['pages'],
    };
}

