/* tslint:disable */
/* eslint-disable */
/**
 * Car Rental API
 * Backend API for Car Rental Application
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserRegister
 */
export interface UserRegister {
    /**
     * User's first name
     * @type {string}
     * @memberof UserRegister
     */
    firstName: string;
    /**
     * User's last name
     * @type {string}
     * @memberof UserRegister
     */
    lastName: string;
    /**
     * User's email address
     * @type {string}
     * @memberof UserRegister
     */
    email: string;
    /**
     * User's phone number
     * @type {string}
     * @memberof UserRegister
     */
    phoneNumber: string;
    /**
     * AWS Cognito user ID (sub claim)
     * @type {string}
     * @memberof UserRegister
     */
    cognitoId: string;
}

/**
 * Check if a given object implements the UserRegister interface.
 */
export function instanceOfUserRegister(value: object): value is UserRegister {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('phoneNumber' in value) || value['phoneNumber'] === undefined) return false;
    if (!('cognitoId' in value) || value['cognitoId'] === undefined) return false;
    return true;
}

export function UserRegisterFromJSON(json: any): UserRegister {
    return UserRegisterFromJSONTyped(json, false);
}

export function UserRegisterFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRegister {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'email': json['email'],
        'phoneNumber': json['phone_number'],
        'cognitoId': json['cognito_id'],
    };
}

export function UserRegisterToJSON(json: any): UserRegister {
    return UserRegisterToJSONTyped(json, false);
}

export function UserRegisterToJSONTyped(value?: UserRegister | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'email': value['email'],
        'phone_number': value['phoneNumber'],
        'cognito_id': value['cognitoId'],
    };
}

