name: Regression Tests

on:
  push:
    branches: ["regression-testing"]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      backend:
        image: your-backend-image
        ports:
          - 8000:8000
      frontend:
        image: your-frontend-image
        ports:
          - 5173:5173

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Postman Tests
        run: |
          npm install -g newman
          newman run login_regression_tests.postman_collection.json -e test_environment.postman_environment.json

      - name: Run Selenium Tests
        run: |
          pip install -r tests/requirements.txt
          pytest tests/test_login_protection.py